//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReportTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmpShortListDistinct
    {
        public string Emp_Id { get; set; }
        public decimal Present_Salary { get; set; }
        public Nullable<System.DateTime> Join_Date { get; set; }
        public Nullable<double> ServiceUpto { get; set; }
        public string Desig_Name { get; set; }
        public string Comp_Name { get; set; }
        public string Dept_Name { get; set; }
        public string Emp_Name { get; set; }
        public Nullable<System.DateTime> Emp_dob { get; set; }
        public string Perm_Add { get; set; }
        public string Pres_Add { get; set; }
        public string CardID { get; set; }
        public string Head_Quarter { get; set; }
        public string Grade_Name { get; set; }
        public Nullable<decimal> TotalOthersAllowance { get; set; }
        public Nullable<decimal> Special { get; set; }
        public string OldID { get; set; }
        public string Area { get; set; }
        public string Zone { get; set; }
        public string Sheet { get; set; }
        public string Section { get; set; }
        public string BankName { get; set; }
        public string TimeZone { get; set; }
        public string Insurance { get; set; }
        public string TimeZoneID { get; set; }
        public string Emp_BGroup { get; set; }
        public string Religion { get; set; }
        public string Emp_Ref1 { get; set; }
        public string Emp_Ref2 { get; set; }
        public string X_Emp { get; set; }
        public string Sex { get; set; }
        public string M_Status { get; set; }
        public string AcademicRecords { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Job_Cat { get; set; }
        public string Job_Type { get; set; }
        public string Emp_Type { get; set; }
        public string Cont_Num { get; set; }
        public string EmailAddress { get; set; }
        public string Personal_Phone { get; set; }
    }
}
